apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-usages
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: deletion-ordering
      functionRef:
        name: function-usages
      input:
        apiVersion: usage.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
              - first-resource
              - second-resource
          - sequence:
              - first-resource
              - third-resource
