---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-usages
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: first-subresource-1
            base:
              apiVersion: nop.crossplane.io/v1alpha1
              kind: NopResource
          - name: first-subresource-2
            base:
              apiVersion: nop.crossplane.io/v1alpha1
              kind: NopResource
          - name: second-resource
            base:
              apiVersion: nop.crossplane.io/v1alpha1
              kind: NopResource
          - name: third-resource
            base:
              apiVersion: nop.crossplane.io/v1alpha1
              kind: NopResource
    - step: deletion-ordering
      functionRef:
        name: function-usages
      input:
        apiVersion: usage.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
              - first-subresource-.*
              - second-resource
