---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-usages
  annotations:
    # This tells crossplane render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: function-usages
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    # FIXME: This is a custom annotation not currently supported by crossplane CLI
    render.crossplane.io/runtime-docker-network: devnet
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.10.1
